apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-microservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-microservice
  template:
    metadata:
      labels:
        app: java-microservice
    spec:
      containers:
        - name: java-microservice
          image: bhargavakulla/java-microservice:1.0
          ports:
            - containerPort: 8080
